###issuesAfter
GET http://localhost:8080/issuesAfter

###issuesBefore
GET http://localhost:8080/issuesBefore

###byNameStandard
GET http://localhost:8080/byName1

<> 2022-07-20T114005.200.json

###byNameCustom
GET http://localhost:8080/byName2

<> 2022-07-20T114018.200.json

###setup
POST http://localhost:8080/setup

###findByLastName
GET http://localhost:8080/personByLastName

###findByFirstName
GET localhost:8080/ivans

###findByYear
GET http://localhost:8080/byYear


###allPerson
GET http://localhost:8080/all


###aggregate
GET http://localhost:8080/aggregate


###update
GET http://localhost:8080/update


###filter
GET http://localhost:8080/filterByName

###personsByCards
GET http://localhost:8080/byCards1

###