###setup
POST http://localhost:8080/setup

###findByLasName
GET http://localhost:8080/personByLastName

###
GET localhost:8080/ivans


###all
GET http://localhost:8080/all


###aggregate
GET http://localhost:8080/aggregate


###update
GET http://localhost:8080/update


###filter
GET http://localhost:8080/filterByName


###