MONGO_HOST: localhost
MONGO_PORT: 27017
micronaut:
  application:
    name: micronautMongoTest
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/micronaut1
netty:
  default:
    allocator:
      max-order: 3
